# .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
printWidth: 105
vueIndentScriptAndStyle: true
overrides:
    - files: '*.hbs'
      options:
          parser: 'angular'
